### ISSUE TITLE
Support CSV dataset files

### ISSUE THREAD

**Issue by ppodgorsek** [ppodgorsek/spring-test-dbunit#107]
It is important to support the datasets that DBUnit provides.

**Comment by paveltrufi** [comment]
would you mind to take a look at my issue, please? https://github.com/springtestdbunit/spring-test-dbunit/issues/162#issue-426096607

**Comment by ppodgorsek** [comment]
@paveltrufi I replied to your comment on that issue. If it doesn't solve your problem, could you create a dedicated separate ticket in this project please?
A general remark about GitHub projects: please do not select random tickets to put comments in, it's always better to create new tickets if none fit the issue you are experiencing. (CSV datasets have nothing to do with your issue)

**Comment by ppodgorsek** [comment]
The CSV support has been done and merged to the master branch.
